# Generated by Django 2.2 on 2020-04-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_auto_20200422_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlenetaccount',
            name='basic_accomplishment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='battlenetaccount',
            name='map_winrate',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='replay',
            name='kills',
            field=models.CharField(default='', max_length=200),
        ),
    ]
