# Generated by Django 2.2 on 2020-03-29 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='新用户', max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('auth', models.CharField(default='', max_length=200)),
                ('has_signin', models.BooleanField(default=False)),
                ('repstats_acc', models.CharField(default='', max_length=100)),
                ('repstats_pwd', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
