# Generated by Django 2.2 on 2020-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='tm_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammate',
            name='nickname',
            field=models.CharField(default='新用户', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammate',
            name='pwd',
            field=models.CharField(default='123456', max_length=100),
        ),
    ]
