# Generated by Django 3.0.4 on 2020-04-04 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200404_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='repstats',
            name='last_sub',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0)),
        ),
    ]
