# Generated by Django 3.0.4 on 2020-04-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_repstats_last_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repstats',
            old_name='last_sub',
            new_name='last_submit',
        ),
    ]
