# Generated by Django 2.2 on 2020-03-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_teammate_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammate',
            name='tm_no',
        ),
    ]
