# Generated by Django 2.2 on 2020-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_teammate_tm_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='repstats_acc',
            field=models.CharField(default='holyca@126.com', max_length=100),
        ),
        migrations.AddField(
            model_name='teammate',
            name='repstats_pwd',
            field=models.CharField(default='', max_length=100),
        ),
    ]
