# Generated by Django 3.0.4 on 2020-04-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200404_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repstats',
            name='last_submit',
        ),
    ]
