# Generated by Django 3.0.4 on 2020-05-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20200510_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='gain',
            field=models.IntegerField(default=0),
        ),
    ]
